// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Despesas.tsx": () => import("../components/mockups/Despesas.tsx"),
  "./components/mockups/FluxoCaixa.tsx": () => import("../components/mockups/FluxoCaixa.tsx")
};
